# Generated by Django 5.0.2 on 2024-03-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('subject', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
